# -*- coding: utf-8 -*-
"""My Horrible Poem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ty7aqb5euaVlLIy9SVJ_c8jAUgSft55e

# My Horrible Poem

My riff on "The Tay Bridge Disaster" by William McGonagall. This poem is considered to be the worst of his all of his poems. I wanted to see if this version could make it better.
"""

from textblob import TextBlob
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

blob = TextBlob(text)

poem = ''
with open('/content/The Tay Bridge Disaster.txt') as f:
  text = f.read()

  words = text.split (" ")

  import random

  random.shuffle(words)

for w in range(len(words)):
  poem += " " + words.pop(0) 

print(poem)
